import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import CapacitySummary from "./capacity";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE} Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CapacitySummary />
    </div>
  );
};

export default Home;
